# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_designer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1463, 698)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reiter = QtWidgets.QTabWidget(self.centralwidget)
        self.reiter.setTabPosition(QtWidgets.QTabWidget.West)
        self.reiter.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.reiter.setObjectName("reiter")
        self.rawXRD = QtWidgets.QWidget()
        self.rawXRD.setObjectName("rawXRD")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rawXRD)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.rawXRD)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.XRDLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.XRDLayout.setContentsMargins(0, 0, 0, 0)
        self.XRDLayout.setObjectName("XRDLayout")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.SliderLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.SliderLayout.setContentsMargins(0, 0, 0, 0)
        self.SliderLayout.setObjectName("SliderLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SliderLayout.addWidget(self.label)
        self.horizontalSliderRaw = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderRaw.setMaximum(100)
        self.horizontalSliderRaw.setSingleStep(0)
        self.horizontalSliderRaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRaw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderRaw.setTickInterval(10)
        self.horizontalSliderRaw.setObjectName("horizontalSliderRaw")
        self.SliderLayout.addWidget(self.horizontalSliderRaw)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.LCDLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.LCDLayout.setContentsMargins(0, 0, 0, 0)
        self.LCDLayout.setObjectName("LCDLayout")
        self.MAInfo = QtWidgets.QLabel(self.layoutWidget1)
        self.MAInfo.setObjectName("MAInfo")
        self.LCDLayout.addWidget(self.MAInfo)
        self.lcdD = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdD.setObjectName("lcdD")
        self.LCDLayout.addWidget(self.lcdD)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.selectorLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.selectorLayout.setContentsMargins(0, 0, 0, 0)
        self.selectorLayout.setObjectName("selectorLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.selectorLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.selectorLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.selectorLayout.addItem(spacerItem)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.container = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.container.setContentsMargins(0, 0, 0, 0)
        self.container.setObjectName("container")
        self.XRDLayoutSpectral = QtWidgets.QVBoxLayout()
        self.XRDLayoutSpectral.setSpacing(0)
        self.XRDLayoutSpectral.setObjectName("XRDLayoutSpectral")
        self.container.addLayout(self.XRDLayoutSpectral)
        self.horizontalLayout.addWidget(self.splitter_2)
        self.reiter.addTab(self.rawXRD, "")
        self.clusteringXRD = QtWidgets.QWidget()
        self.clusteringXRD.setObjectName("clusteringXRD")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.clusteringXRD)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.clusteringXRD)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_3)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.posClusterLayoutCon = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.posClusterLayoutCon.setContentsMargins(0, 0, 0, 0)
        self.posClusterLayoutCon.setObjectName("posClusterLayoutCon")
        self.posClusterLayout = QtWidgets.QVBoxLayout()
        self.posClusterLayout.setObjectName("posClusterLayout")
        self.posClusterLayoutCon.addLayout(self.posClusterLayout)
        self.widget = QtWidgets.QWidget(self.splitter_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.setNumberclusters = QtWidgets.QSpinBox(self.widget)
        self.setNumberclusters.setMinimum(2)
        self.setNumberclusters.setObjectName("setNumberclusters")
        self.horizontalLayout_2.addWidget(self.setNumberclusters)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBoxClusterMethods = QtWidgets.QComboBox(self.widget)
        self.comboBoxClusterMethods.setObjectName("comboBoxClusterMethods")
        self.comboBoxClusterMethods.addItem("")
        self.comboBoxClusterMethods.addItem("")
        self.comboBoxClusterMethods.addItem("")
        self.comboBoxClusterMethods.addItem("")
        self.comboBoxClusterMethods.addItem("")
        self.comboBoxClusterMethods.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxClusterMethods)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.widget1 = QtWidgets.QWidget(self.splitter_3)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.setEps = QtWidgets.QLineEdit(self.widget1)
        self.setEps.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setEps.setMaxLength(21)
        self.setEps.setObjectName("setEps")
        self.horizontalLayout_3.addWidget(self.setEps)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.setNMin = QtWidgets.QLineEdit(self.widget1)
        self.setNMin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setNMin.setMaxLength(21)
        self.setNMin.setObjectName("setNMin")
        self.horizontalLayout_3.addWidget(self.setNMin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widget2 = QtWidgets.QWidget(self.splitter_3)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.comboBoxMetric = QtWidgets.QComboBox(self.widget2)
        self.comboBoxMetric.setObjectName("comboBoxMetric")
        self.comboBoxMetric.addItem("")
        self.comboBoxMetric.addItem("")
        self.comboBoxMetric.addItem("")
        self.comboBoxMetric.addItem("")
        self.comboBoxMetric.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxMetric)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.setNMin_2 = QtWidgets.QLineEdit(self.widget2)
        self.setNMin_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setNMin_2.setMaxLength(21)
        self.setNMin_2.setObjectName("setNMin_2")
        self.horizontalLayout_4.addWidget(self.setNMin_2)
        self.horizontalLayout_5.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.clusteringXRD)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.pdMatrixLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.pdMatrixLayout.setContentsMargins(0, 0, 0, 0)
        self.pdMatrixLayout.setObjectName("pdMatrixLayout")
        self.widget3 = QtWidgets.QWidget(self.splitter_4)
        self.widget3.setObjectName("widget3")
        self.buttonsLayouttop = QtWidgets.QHBoxLayout(self.widget3)
        self.buttonsLayouttop.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayouttop.setObjectName("buttonsLayouttop")
        self.buttonslayoutbott = QtWidgets.QVBoxLayout()
        self.buttonslayoutbott.setObjectName("buttonslayoutbott")
        self.clusterButton = QtWidgets.QPushButton(self.widget3)
        self.clusterButton.setObjectName("clusterButton")
        self.buttonslayoutbott.addWidget(self.clusterButton)
        self.pdButton = QtWidgets.QPushButton(self.widget3)
        self.pdButton.setObjectName("pdButton")
        self.buttonslayoutbott.addWidget(self.pdButton)
        self.mdsButton = QtWidgets.QPushButton(self.widget3)
        self.mdsButton.setObjectName("mdsButton")
        self.buttonslayoutbott.addWidget(self.mdsButton)
        self.buttonsLayouttop.addLayout(self.buttonslayoutbott)
        spacerItem2 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayouttop.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.splitter_4)
        self.mdsLayoutCon = QtWidgets.QHBoxLayout()
        self.mdsLayoutCon.setObjectName("mdsLayoutCon")
        self.mdsLayout = QtWidgets.QVBoxLayout()
        self.mdsLayout.setObjectName("mdsLayout")
        self.mdsLayoutCon.addLayout(self.mdsLayout)
        self.horizontalLayout_5.addLayout(self.mdsLayoutCon)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.reiter.addTab(self.clusteringXRD, "")
        self.decompositionXRD = QtWidgets.QWidget()
        self.decompositionXRD.setObjectName("decompositionXRD")
        self.splitter_5 = QtWidgets.QSplitter(self.decompositionXRD)
        self.splitter_5.setGeometry(QtCore.QRect(0, 10, 1370, 593))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter_6)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.scatterDecompositionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.scatterDecompositionLayout.setContentsMargins(0, 0, 0, 0)
        self.scatterDecompositionLayout.setObjectName("scatterDecompositionLayout")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.SliderLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.SliderLayout_2.setContentsMargins(0, 0, 0, 0)
        self.SliderLayout_2.setObjectName("SliderLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.SliderLayout_2.addWidget(self.label_9)
        self.horizontalSliderRaw_2 = QtWidgets.QSlider(self.layoutWidget_2)
        self.horizontalSliderRaw_2.setMaximum(100)
        self.horizontalSliderRaw_2.setSingleStep(0)
        self.horizontalSliderRaw_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRaw_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderRaw_2.setTickInterval(10)
        self.horizontalSliderRaw_2.setObjectName("horizontalSliderRaw_2")
        self.SliderLayout_2.addWidget(self.horizontalSliderRaw_2)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.LCDLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.LCDLayout_2.setContentsMargins(0, 0, 0, 0)
        self.LCDLayout_2.setObjectName("LCDLayout_2")
        self.MAInfo_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.MAInfo_2.setObjectName("MAInfo_2")
        self.LCDLayout_2.addWidget(self.MAInfo_2)
        self.lcdD_2 = QtWidgets.QLCDNumber(self.layoutWidget_3)
        self.lcdD_2.setObjectName("lcdD_2")
        self.LCDLayout_2.addWidget(self.lcdD_2)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.selectorLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.selectorLayout_2.setContentsMargins(0, 0, 0, 0)
        self.selectorLayout_2.setObjectName("selectorLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.selectorLayout_2.addWidget(self.label_10)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.selectorLayout_2.addWidget(self.comboBox_3)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.selectorLayout_2.addWidget(self.label_11)
        self.setNoVec = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.setNoVec.setMinimum(2)
        self.setNoVec.setObjectName("setNoVec")
        self.selectorLayout_2.addWidget(self.setNoVec)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.selectorLayout_2.addWidget(self.label_12)
        self.setShoVec = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.setShoVec.setObjectName("setShoVec")
        self.selectorLayout_2.addWidget(self.setShoVec)
        self.pushButtonNMF = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButtonNMF.setObjectName("pushButtonNMF")
        self.selectorLayout_2.addWidget(self.pushButtonNMF)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.selectorLayout_2.addItem(spacerItem3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.splitter_5)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.container_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.container_2.setContentsMargins(0, 0, 0, 0)
        self.container_2.setObjectName("container_2")
        self.DecompositionSpectralLayout = QtWidgets.QVBoxLayout()
        self.DecompositionSpectralLayout.setSpacing(0)
        self.DecompositionSpectralLayout.setObjectName("DecompositionSpectralLayout")
        self.container_2.addLayout(self.DecompositionSpectralLayout)
        self.reiter.addTab(self.decompositionXRD, "")
        self.cuts = QtWidgets.QWidget()
        self.cuts.setObjectName("cuts")
        self.reiter.addTab(self.cuts, "")
        self.matching = QtWidgets.QWidget()
        self.matching.setObjectName("matching")
        self.reiter.addTab(self.matching, "")
        self.verticalLayout.addWidget(self.reiter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1463, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionComposition = QtWidgets.QAction(MainWindow)
        self.actionComposition.setCheckable(False)
        self.actionComposition.setObjectName("actionComposition")
        self.actionPosition = QtWidgets.QAction(MainWindow)
        self.actionPosition.setObjectName("actionPosition")
        self.actionXRD = QtWidgets.QAction(MainWindow)
        self.actionXRD.setObjectName("actionXRD")
        self.actionFunction = QtWidgets.QAction(MainWindow)
        self.actionFunction.setObjectName("actionFunction")
        self.actionAngle = QtWidgets.QAction(MainWindow)
        self.actionAngle.setObjectName("actionAngle")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionPrevious_Analysis = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Analysis.setObjectName("actionPrevious_Analysis")
        self.menuLoad.addAction(self.actionComposition)
        self.menuLoad.addAction(self.actionPosition)
        self.menuLoad.addAction(self.actionXRD)
        self.menuLoad.addAction(self.actionAngle)
        self.menuLoad.addAction(self.actionFunction)
        self.menuLoad.addSeparator()
        self.menuLoad.addAction(self.actionPrevious_Analysis)
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.reiter.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "X"))
        self.MAInfo.setText(_translate("MainWindow", "Measurement Area Info"))
        self.label_2.setText(_translate("MainWindow", "Color-Coded"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Coordinates"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Binary"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Ternary"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Quaternary"))
        self.reiter.setTabText(self.reiter.indexOf(self.rawXRD), _translate("MainWindow", "Raw XRD/Raman"))
        self.label_3.setText(_translate("MainWindow", "Clusters:"))
        self.label_4.setText(_translate("MainWindow", "Method:"))
        self.comboBoxClusterMethods.setItemText(0, _translate("MainWindow", "KMeans"))
        self.comboBoxClusterMethods.setItemText(1, _translate("MainWindow", "AgglomWard"))
        self.comboBoxClusterMethods.setItemText(2, _translate("MainWindow", "AgglomAvg"))
        self.comboBoxClusterMethods.setItemText(3, _translate("MainWindow", "AgglomComplete"))
        self.comboBoxClusterMethods.setItemText(4, _translate("MainWindow", "SpectralClustering"))
        self.comboBoxClusterMethods.setItemText(5, _translate("MainWindow", "DBScan"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Coordinates"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Binary"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Ternary"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Quaternary"))
        self.label_5.setText(_translate("MainWindow", "eps:"))
        self.setEps.setText(_translate("MainWindow", "0.03"))
        self.label_6.setText(_translate("MainWindow", "Nmin:"))
        self.setNMin.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "Metric/Measure"))
        self.comboBoxMetric.setItemText(0, _translate("MainWindow", "euclidean"))
        self.comboBoxMetric.setItemText(1, _translate("MainWindow", "l1"))
        self.comboBoxMetric.setItemText(2, _translate("MainWindow", "l2"))
        self.comboBoxMetric.setItemText(3, _translate("MainWindow", "manhattan"))
        self.comboBoxMetric.setItemText(4, _translate("MainWindow", "cosine"))
        self.label_8.setText(_translate("MainWindow", "param:"))
        self.clusterButton.setText(_translate("MainWindow", "Cluster!"))
        self.pdButton.setText(_translate("MainWindow", "PD Matrix!"))
        self.mdsButton.setText(_translate("MainWindow", "MDS 2D!"))
        self.reiter.setTabText(self.reiter.indexOf(self.clusteringXRD), _translate("MainWindow", "Clustering"))
        self.label_9.setText(_translate("MainWindow", "X"))
        self.MAInfo_2.setText(_translate("MainWindow", "Measurement Area Info"))
        self.label_10.setText(_translate("MainWindow", "Color-Coded"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Coordinates"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Binary"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Ternary"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Quaternary"))
        self.label_11.setText(_translate("MainWindow", "# Base Vectors"))
        self.label_12.setText(_translate("MainWindow", "Show Vector "))
        self.pushButtonNMF.setText(_translate("MainWindow", "Do NNMF!"))
        self.reiter.setTabText(self.reiter.indexOf(self.decompositionXRD), _translate("MainWindow", "Decomposition"))
        self.reiter.setTabText(self.reiter.indexOf(self.cuts), _translate("MainWindow", "QB Cuts"))
        self.reiter.setTabText(self.reiter.indexOf(self.matching), _translate("MainWindow", "Matching"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.actionComposition.setText(_translate("MainWindow", "Composition"))
        self.actionComposition.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionPosition.setText(_translate("MainWindow", "Position"))
        self.actionPosition.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionXRD.setText(_translate("MainWindow", "XRD/Raman"))
        self.actionXRD.setShortcut(_translate("MainWindow", "Ctrl+Shift+X"))
        self.actionFunction.setText(_translate("MainWindow", "Function"))
        self.actionFunction.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionAngle.setText(_translate("MainWindow", "Angle"))
        self.actionAngle.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.actionQuit.setText(_translate("MainWindow", "About"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
        self.actionPrevious_Analysis.setText(_translate("MainWindow", "Previous Analysis"))

